// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMu31b43dUeqOjl51HM6vVfd47K00ktgQ',
    appId: '1:957060511196:web:11d87268270481b2624b19',
    messagingSenderId: '957060511196',
    projectId: 'longboardapp-9e6ba',
    authDomain: 'longboardapp-9e6ba.firebaseapp.com',
    storageBucket: 'longboardapp-9e6ba.appspot.com',
    measurementId: 'G-2MN7G0QZ3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKCMhbSJLct0GnvNNQWjFtQMdf_gM7CzI',
    appId: '1:957060511196:android:2243d02ca32c1086624b19',
    messagingSenderId: '957060511196',
    projectId: 'longboardapp-9e6ba',
    storageBucket: 'longboardapp-9e6ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHNWTG1j-AN_DAaCkRaF7g-A4y0oUGB7g',
    appId: '1:957060511196:ios:9b1a228ea7362ec6624b19',
    messagingSenderId: '957060511196',
    projectId: 'longboardapp-9e6ba',
    storageBucket: 'longboardapp-9e6ba.appspot.com',
    iosClientId: '957060511196-go4t6gv59v5ngg0pce6omj3fn7va7vct.apps.googleusercontent.com',
    iosBundleId: 'io.soupy.longboardapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHNWTG1j-AN_DAaCkRaF7g-A4y0oUGB7g',
    appId: '1:957060511196:ios:91398cfe723d4ed6624b19',
    messagingSenderId: '957060511196',
    projectId: 'longboardapp-9e6ba',
    storageBucket: 'longboardapp-9e6ba.appspot.com',
    iosClientId: '957060511196-98k9tf66r0uitmae40513l3db1k1vpkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.longboardapp.RunnerTests',
  );
}
